sipAdmin/adminTablet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from index import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^index/',include('index.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

sipAdmin/index/urls.py
from django.conf.urls import url
from . import views

app_name = 'index'

urlpatterns = [
    url(r'^login/$', views.user_login, name='login'),
    url(r'^change/$', views.change, name='change'),
    #url(r'^network/$', views.user_login, name='network'),
    url(r'^sip/$', views.sips, name='sip'),
    # url(r'^info/$', views.user_create, name='info'),

]

sipAdmin/index/models.py
from django.db import models

class SipModel(models.Model):
    sip_name = models.CharField(max_length=255, blank=True)
    sip_pass = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.sip_name

sipAdmin/index/forms.py
from django import forms
from index.models import SipModel
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password')


class SipUserForm(forms.ModelForm):

	class Meta():
		model = SipModel
		fields = ('sip_name','sip_pass')

sipAdmin/index/views.py
from django.shortcuts import render
from index.forms import UserForm, SipUserForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from index.models import SipModel
from index.confproc import manager

def index(request):
    return render(request, 'index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def change(request):
    if request.method == 'POST':
        new_username = request.POST.get('username')
        new_password = request.POST.get('password')
        cur_user = list(get_user_model().objects.filter(is_superuser=True).values_list('username', flat=True))
        user = get_user_model().objects.get(username=cur_user[0])
        user.username = new_username
        user.set_password(new_password)
        user.save()
        return HttpResponseRedirect("/index/login")

    return render(request, 'change.html', {})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login.html', {})

def sips(request):
    if request.method == 'POST':
        form = SipUserForm(request.POST)
        form.save()
        sip_name = request.POST.get('sip_pass')
        sip_pass = request.POST.get('sip_pass')

        work_dir = '/etc/asterisk/'

        sip_conf_path = work_dir + 'sip.conf'

        m = manager(work_dir)

        print(m.add_user(sip_name, sip_pass))

        print(m.commit())

        #TODO: Send to json 
        return HttpResponseRedirect("/")

    return render(request, 'sipclient.html',{})
# Create your views here.

sipAdmin/index/templates/base.html
<!DOCTYPE html>
<html>
  {% load static %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">  </head>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    {% if user.is_authenticated %}
      <div class="header">
        <img src="{% static 'img/logo.svg' %}" height="140" width="240" />
        <a href="{% url 'logout' %}"> Выход <img src="{% static 'img/logout.svg' %}" height="50" width="50" /></a>
        <a href="{% url 'index:change' %}"> Смена пароля</a>
      </div> 
    {% else %}
      <div class="header">
        <img src="{% static 'img/logo.svg' %}" height="140" width="240" />
      </div> 
    {% endif %}


  </head>

  <body>
    <div class="topnav">
          {% if user.is_authenticated %}
            <topnav><a href="{% url 'index' %}">Главная</a></topnav>
            <topnav><a href="{% url 'index:sip' %}">Добавление sip аккаунта</a></topnav>          
          {% else %}
            <topnav><a href="{% url 'index:login' %}">Вход</a></topnav>
          {% endif %}
      </div>
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

sipAdmin/index/templates/change.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Change userame and Password</h1>
<form method="post" action="{% url 'index:change' %}">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Change">
</form>
</div>
  </div>
{% endblock %}

sipAdmin/index/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Добро пожаловать в админ панель SIP устройства</h1>
  </div>
</div>
{% endblock %}

sipAdmin/index/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login</h1>
        <form class="form-inline" method="post" action="{% url 'index:login' %}">
          {% csrf_token %}
          
          <label for="username">Имя пользователя:</label>
          <input type="text" name="username" placeholder="Username">
          
          <label for="password">Пароль:</label>
          <input type="password" name="password" placeholder="Password">  
          
          <button type="submit">Войти</button>
        </form>
</div>
  </div>
{% endblock %}

sipAdmin/index/templates/sipclient.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Sip</h1>
        <form class="form-inline" method="post" action="{% url 'index:sip' %}">
          {% csrf_token %}
          <label for="sip_name">Имя SIP аккаунта:</label>
          <input type="text" name="sip_name" placeholder="sip_name">
          <label for="sip_pass">Пароль SIP аккаунта:</label>
          <input type="text" name="sip_pass" placeholder="sip_pass">
          <button type="submit">Добавить нового SIP пользователя</button>
</form>
</div>
  </div>
{% endblock %}